#define SMALL_BOARD_WIDTH 60
#define SMALL_BOARD_HEIGHT 34
#define SMALL_DRAW_SCALE 4 // WARNING: IF THIS NUMBER IS NOT EVEN, THIS CODE WILL NOT WORK
#define SMALL_INITIAL_LENGTH 20

#define LARGE_BOARD_WIDTH 120
#define LARGE_BOARD_HEIGHT 70
#define LARGE_DRAW_SCALE 2 // WARNING: IF THIS NUMBER IS NOT EVEN, THIS CODE WILL NOT WORK
#define LARGE_INITIAL_LENGTH 30

extern u32 SNAKE_BOARD_WIDTH;
extern u32 SNAKE_BOARD_HEIGHT;
extern u32 DRAW_SCALE;
extern u32 SNAKE_INITIAL_LENGTH;

#define SCORE_BOX_Y SNAKE_BOARD_HEIGHT * DRAW_SCALE

#define GAME_OVER_DURATION 150
#define GAME_FRAME_DELAY 50

#define SNAKE_START_X 20
#define SNAKE_START_Y 20
#define SNAKE_INITIAL_FACING RIGHT
#define MAX_TURN_COUNT 50

#define FOOD_DURATION 200
#define FOOD_LENGTH_INCREMENT 5
#define FOOD_GENERATION_PROBABILITY_ONE_IN 50
#define MAX_FOOD_COUNT 5
#define FOODCOUNT(score) ((score) < 5000 ? 1 : ((score) < 10000 ? 2 : 3))
#define SNAKESPEED(score) 1

#define BACKGROUND_COLOR BLACK
#define WALL_COLOR RED
#define SNAKE_COLOR GREEN
#define FOOD_COLOR WHITE
#define SCORE_COLOR YELLOW
#define SCORE_BACKGROUND_COLOR GRAY

#define SPLASH_COUNTDOWN 2000

#define DEBUG_MODE 0

void setMapSize(u16 mapSize);
